# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: wecube_plugins_itsdangerous v0.2.1\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-02-24 10:45+0800\n"
"PO-Revision-Date: 2021-02-24 10:45+0800\n"
"Last-Translator: wecube <EMAIL@ADDRESS>\n"
"Language-Team: zh-CN <LL@li.org>\n"
"Language: zh-CN \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:92
msgid "failed to acquire lock, package cache may not be available"
msgstr ""

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:390
#: ../wecube_plugins_itsdangerous/apps/processor/api.py:453
msgid "Instance Ids"
msgstr ""

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:390
#: ../wecube_plugins_itsdangerous/apps/processor/api.py:453
msgid "Line"
msgstr ""

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:390
#: ../wecube_plugins_itsdangerous/apps/processor/api.py:453
msgid "Content"
msgstr ""

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:390
#: ../wecube_plugins_itsdangerous/apps/processor/api.py:453
msgid "Message"
msgstr ""

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:390
#: ../wecube_plugins_itsdangerous/apps/processor/api.py:453
msgid "Source Script"
msgstr ""

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:544
#, python-format
msgid "missing query param: %(attribute)s, eg. /v1/api?%(attribute)s=value"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/controller.py:44
#: ../wecube_plugins_itsdangerous/common/controller.py:62
#: ../wecube_plugins_itsdangerous/common/controller.py:91
msgid "data must be list type"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/controller.py:124
msgid "data must be dict type"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/exceptions.py:30
msgid "Plugin Business Processing Error"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/exceptions.py:40
msgid "Field Missing"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/exceptions.py:44
#, python-format
msgid "column: %(attribute)s must be specific"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/exceptions.py:54
msgid "Validation Error"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/exceptions.py:58
#, python-format
msgid "column %(attribute)s validate failed, because: %(msg)s"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/exceptions.py:74
#, python-format
msgid "the resource(%(resource)s) you request not found"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/exceptions.py:84
msgid "Batch Operation Partial Error"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/exceptions.py:88
#, python-format
msgid "fail to %(action)s [%(num)s] record, detail error in the data block"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/exceptions.py:98
msgid "Conflict"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/exceptions.py:102
#, python-format
msgid "object[%(oid)s] is used by %(name)s"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/s3.py:32
msgid "invalid s3 endpoint url, eg: schema://host[:port]/bucket/object"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/s3.py:48
#, python-format
msgid "failed to download file[%(filepath)s] from s3: %(reason)s"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/utils.py:94
msgid "Connection Error"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/utils.py:95
msgid "Failed to establish a new connection"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/utils.py:101
msgid "Timeout Error"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/utils.py:102
msgid "Server do not respond"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/utils.py:111
msgid "Not Found"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/utils.py:112
msgid "The resource you request not exist"
msgstr ""

#: ../wecube_plugins_itsdangerous/common/utils.py:126
msgid "Server Error"
msgstr ""

#: ../wecube_plugins_itsdangerous/db/resource.py:23
#: ../wecube_plugins_itsdangerous/db/validator.py:33
#, python-format
msgid "reference of %(resource)s(%(id)s) not found"
msgstr ""

#: ../wecube_plugins_itsdangerous/db/resource.py:230
#: ../wecube_plugins_itsdangerous/db/resource.py:236
#, python-format
msgid "%(value)s is not acceptable, use %(fixed_value)s instead"
msgstr ""

#: ../wecube_plugins_itsdangerous/db/resource.py:449
msgid "specify at least one field content"
msgstr ""

#: ../wecube_plugins_itsdangerous/db/validator.py:17
#, python-format
msgid "expected string, not %(type)s "
msgstr ""

#: ../wecube_plugins_itsdangerous/db/validator.py:20
#, python-format
msgid "length required: %(min)d <= %(value)d <= %(max)d"
msgstr ""

#: ../wecube_plugins_itsdangerous/db/validator.py:45
#, python-format
msgid "expected %(choices)s, not %(value)s"
msgstr ""

#: ../wecube_plugins_itsdangerous/db/validator.py:48
#, python-format
msgid "value should be >= 1, not %(value)s"
msgstr ""

#: ../wecube_plugins_itsdangerous/db/validator.py:50
#, python-format
msgid "expected string in %(choices)s or int(>=1), not %(type)s "
msgstr ""

#: talos ValidationError
#, python-format
msgid "detail: column %(attribute)s validate failed, because: %(msg)s"
msgstr ""
